name: Publish osucore wheels
on:
  push:
    branches:
      - 'rust'

jobs:
  publish_pypi_wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11']
      fail-fast: false
    environment: osucore
    env:
      MATURIN_PYPI_TOKEN: ${{ secrets.MATURIN_PYPI_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: Wandalen/wretry.action@master
      with:
        action: PyO3/maturin-action@v1
        with: |
          maturin-version: "v0.13.7"
          command: publish
          args: --manifest-path osucore/Cargo.toml -i ${{ matrix.python-version }} --no-sdist --universal2
        attempt_limit: 3
        attempt_delay: 10000

  publish_pypi_sdist:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.9']
      fail-fast: false
    environment: osucore
    env:
      MATURIN_PYPI_TOKEN: ${{ secrets.MATURIN_PYPI_TOKEN }}
    steps:
    - uses: actions/checkout@v3
    - uses: dtolnay/rust-toolchain@stable
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: Wandalen/wretry.action@master
      with:
        action: PyO3/maturin-action@v1
        with: |
          maturin-version: "v0.13.7"
          command: publish
          args: --manifest-path osucore/Cargo.toml
          container: off
        attempt_limit: 3
        attempt_delay: 10000
